### ISSUE TITLE
request for comments: public JSON API

### ISSUE THREAD

**Issue by kmyk** [online-judge-tools/api-client#2]
@fukatani @Tatamo @kjnh10
online-judge-tools のライブラリ部分を分離して (もとからある Python API の他に) それを利用してツールを開発する人向けのコマンドを用意しました。JSON を吐きます。https://github.com/kmyk/online-judge-tools/issues/687 で面倒だからやらないとか言ってたやつです。
JSON API は README に書いた仕様のものを予定していますが、なにかやばそうなところないか確認するのを手伝ってほしいです。後から気づくと互換性の問題が起きるので先に見つけておきたい。よろしくお願いします。

**Comment by fukatani** [comment]
- get-problemのアルファベットはコードフォーシズで見られる"E2"みたいな形式やyukicoderの数字だけのIDも含まれますか？
- 浮動小数点を出力とする問題の許容誤差などのプロパティが将来足されることはありますか？後からでも足す分には大きな問題はない？

- ojのAtCoderSubmissionに相当しているものも使ってはいるので将来的には欲しいです。

**Comment by kmyk** [comment]
* `E2` みたいなのもあります。例を見たことはないですが、サイトによっては `1` とか `second` もありえるでしょう
    * yukicoder は普通に `A` `B` `C` です。問題自体の id とコンテストと問題間の関係の属性である alphabet を混同しないでください。たとえば https://atcoder.jp/contests/atc002/tasks/abc007_3 と https://atcoder.jp/contests/abc007/tasks/abc007_3 はまったく同一の問題ですが alphabet の値は異なります
* 将来足されるかは分かりません。後から足す分には問題はありません
     * これは API client であって analyzer ではありません。なので、許容誤差などの情報がその役割の範囲内かどうかは議論の余地があります
     * 今回気にしている互換性の問題は、なにかを減らしたり変更したりするときにのみ発生します
* 「AtCoderSubmission に相当しているもの」とは正確にはなんですか？ 提出用のサブコマンドは提出結果の URL を返しますが、これでは不足ですか？

**Comment by fukatani** [comment]
- alphabetは名前も必ずしも正しくないし、説明もわかりやすくないですが、代案もありません。

- 「AtCoderSubmission に相当しているもの」とは正確にはなんですか？ 提出用のサブコマンドは提出結果の URL を返しますが、これでは不足ですか？

rujaionで提出の途中経過を取得してポップアップしています。
提出のURLからstateを出力するapiを欲しています。

**Comment by kmyk** [comment]
> rujaionで提出の途中経過を取得してポップアップしています。
提出のURLからstateを出力するapiを欲しています。

理解しました。その用途で欲しいと思う人がいるのは分かるし、一貫性の意味でも追加はよさそうだと思います。
一方で、途中経過を取得してポップアップすることに (私は) 魅力を感じません (それができてもレートは上がらなさそうなので)。とりあえず issue (#3) を立てて、実装してくれる人が現れるのを待つことにします。

**Comment by kmyk** [comment]
もういまさら変更はなさそうだし閉じ
