### ISSUE TITLE
Failed CI because old GCJ judges are disappeared

### ISSUE THREAD

**Issue by yosupo06** [online-judge-tools/api-client#36]
It seems that we can not access old GCJ problems  (e.g. https://codingcompetitions.withgoogle.com/codejam/archive/2013 )

I believe that Google is replacing it to new GCJ judge (and tests for old GCJ are no longer needs), but no confidence.

**Comment by kmyk** [comment]
It seems correct that GCJ is trying to port old problems to the new platform. I'll just mark tests as `@unittest.skipIf` and remove them after a while.
