### ISSUE TITLE
error by trying to get test cases of GCJ problems whose test cases are not combined to a single sample case

### ISSUE THREAD

**Issue by tko919** [online-judge-tools/api-client#46]
GCJでテストケースが複数存在する問題のダウンロードを行おうとするとエラーが発生します
OS:Windows10
online-judge-tools: 10.0.8
```
$ oj dl https://codingcompetitions.withgoogle.com/kickstart/round/000000000019ffc7/00000000001d3ff3
[ERROR] the number of <pre class="io-content"> is not two
```

**Comment by kmyk** [comment]
報告ありがとうございます。

非想定のケースなのでエラーになっています。いままで GCJ でサンプルケースが複数になることはない (常にひとつのサンプルケースににまとめられるはず) と思っていました。

---

問題の箇所:

https://github.com/online-judge-tools/api-client/blob/3cf62f827374b920630d46fc14f1b35b49e226db/onlinejudge/service/google.py#L92-L108

https://codingcompetitions.withgoogle.com/kickstart/round/000000000019ffc7/00000000001d3ff3

**Comment by kmyk** [comment]
そのうち修正するので待っててください。早めに直しておきたい場合はプルリクをお願いします
