### ISSUE TITLE
Downloading system cases of AtCoder from the Dropbox

### ISSUE THREAD

**Issue by kmyk** [online-judge-tools/api-client#60]
## Description

We can download system cases of some problems of AtCoder, because AtCoder distributes some test cases via Dropbox.
This feature is desired by users. However, while technically possible, I'm not sure if it's acceptable in terms of morality and maintainability.

## Possible implementations and the analysis

選択肢:

1. Dropbox の App として正規の API を使ってダウンロードする
2. Dropbox を scraping する

過去の議論:

> しかし、しんどいので私は実装もメンテもあまりしたくないです。(ユーザからは望まれてるので、よく書けたプルリクが来てしまった場合はマージせざるをえないみたいなところはありますが……)
> これは以下のふたつの課題のためです:
>
> 1. Dropbox の操作が難しい
>     - Dropbox は scraping を歓迎していません。サイトが AtCoder などと違って複雑かつ頻繁に変更が入るので、scraping は開発もメンテもしんどいはずです。ちなみにユーザにとっては楽です
>         - 追記: 規約違反の可能性がある (ない可能性もある) ので確認が必要
>     - API の利用は推奨されていますが、開発者にとってもユーザにとってもしんどいです。開発者側は OAuth 用のサーバを立てて維持管理をする必要がありますし、ユーザ側は Dropbox のアカウントを作って認証その他をする必要があります (たぶん)
>     - 参考: https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/download-file-using-python-API-frpm-another-user/td-p/191824
> 2. AtCoder はテストケースのダウンロードの自動化を歓迎していない
>    - 「望まれているのは分かるけど、機械的にダウンロードできるようにしちゃうと他のオンラインジャッジに問題を丸パクリされるのでつらい」みたいな話があります。実装前に chokudai さんに話を通す必要があります

_Originally posted by @kmyk in https://github.com/online-judge-tools/verification-helper/issues/74#issuecomment-621939900_

## Other notes

-   [AtCoder のテストケース - AtCoder](https://atcoder.jp/posts/20)
-   existing tools
    -   AtCoder TestCase Extension https://greasyfork.org/ja/scripts/371832-atcoder-testcase-extension
        -   [AtCoderの拡張機能を3つ作った話 - tatsumack blog](http://tatsumack.hatenablog.com/entry/2018/12/09/113908)
    -   takoha-cpp/WrongAnswer https://github.com/takoha-cpp/WrongAnswer
-   related issues
    -   in oj: https://github.com/online-judge-tools/oj/issues/144 (closed)
    -   in verification-helper: https://github.com/online-judge-tools/verification-helper/issues/74

**Comment by kmyk** [comment]
これは現状の整理のための issue です。
https://github.com/takoha-cpp/WrongAnswer を見かけたので立てました。

ところで takoha-cpp/WrongAnswer みたいなのを plugin 扱いで叩けるようにする方針は他のものと比べてありな気がする。少なくとも online-judge-tools 側のメンテの負担は減る。ただしメンテの負担が plugin 側に移るだけで、どれくらい適切にメンテを続けてくれるか分からないという問題はある。AtCoder 側が嫌がるという問題がどうなるかは分かりません。すでにあるツールの wrapper を書くだけならぎりぎり許されたりしないか？

**Comment by qryxip** [comment]
AtCoderのDropboxの全ファイルを取得し、軽く調べてみました。(後でsnowchainsにも反映させたい)

https://gist.github.com/qryxip/ae7ccc41c879ffe705f4beded9a2c685

これを踏まえるとwaよりもシンプルな実装で対処できるのでは?と思ったので、こっち(api-client)かverification-helperで実装するというのはどうでしょうか。私か誰かが`download-atcoder-testcases(1)`のようなものを作ってそれを叩くというのも良いと思いますが。

**Comment by kmyk** [comment]
@qryxip あなたのコードをとても参考にして実装してみたのですが、動きません。原因を知ってたら教えてください。
そもそも snowchains の方では動いていますか？

https://github.com/online-judge-tools/api-client/tree/atcoder-system-cases
https://github.com/online-judge-tools/oj/tree/atcoder-system-cases

``` console
$ oj d -n -a https://atcoder.jp/contests/abc100/tasks/abc100_a --dropbox-token=XXXXXXXXXXXXXXXXXXXXXXXXXX
[INFO] online-judge-tools 11.1.3 (+ online-judge-api-client 10.8.0)
[INFO] problem recognized: AtCoderProblem.from_url('https://atcoder.jp/contests/abc100/tasks/abc100_a'): https://atcoder.jp/contests/abc100/tasks/abc100_a
[INFO] load cookie from: /home/user/.local/share/online-judge-tools/cookie.jar
[NETWORK] POST: https://api.dropboxapi.com/2/files/list_folder
[NETWORK] 200 OK
[INFO] contest folder found: {'.tag': 'folder', 'name': 'ARC113', 'id': 'id:hjsYZQdnqVAAAAAAAAFZeA'}
[NETWORK] POST: https://api.dropboxapi.com/2/files/list_folder
[NETWORK] 200 OK
[INFO] problem folder found: {'.tag': 'folder', 'name': 'D', 'id': 'id:hjsYZQdnqVAAAAAAAADA8A'}
[NETWORK] POST: https://api.dropboxapi.com/2/files/list_folder
[NETWORK] 200 OK
[NETWORK] POST: https://content.dropboxapi.com/2/sharing/get_shared_link_file
[NETWORK] 409 Conflict
[ERROR] 409 Client Error: Conflict for url: https://content.dropboxapi.com/2/sharing/get_shared_link_file
Traceback (most recent call last):
  File "/home/user/GitHub/online-judge-tools/onlinejudge_command/main.py", line 281, in main
    run_program(parsed, parser=parser)
  File "/home/user/GitHub/online-judge-tools/onlinejudge_command/main.py", line 247, in run_program
    download(args)
  File "/home/user/GitHub/online-judge-tools/onlinejudge_command/subcommand/download.py", line 66, in download
    samples = problem.download_system_cases(session=sess)
  File "/home/user/GitHub/online-judge-api-client/onlinejudge/service/atcoder.py", line 925, in download_system_cases
    data_in = self._get_dropbox_shared_link_file(path=path_in, shared_link=shared_link, session=session)
  File "/home/user/GitHub/online-judge-api-client/onlinejudge/service/atcoder.py", line 868, in _get_dropbox_shared_link_file
    resp.raise_for_status()
  File "/home/user/.local/lib/python3.6/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://content.dropboxapi.com/2/sharing/get_shared_link_file
```

**Comment by qryxip** [comment]
権限の問題なら`400`が来るはずなので原因は"reached its user limit"の方なんじゃないかと思います。

**Comment by qryxip** [comment]
ちなみに今の実装はこれです。多分大体の「人の手による暖かみ」に対応していると思います。

- https://github.com/qryxip/snowchains/blob/f3a1a7788eccbaa8428e6443f7b5d4e698b3f834/snowchains_core/src/web/atcoder.rs#L216-L465
- https://github.com/qryxip/snowchains/blob/f3a1a7788eccbaa8428e6443f7b5d4e698b3f834/snowchains_core/resources/dropbox-path-prefixes.json

##### 暖かみの例

- CODE FESTIVAL
- ファイル名, そもそも`in`と`out`の構成になっていない ([以前貼ったGist](https://gist.github.com/qryxip/ae7ccc41c879ffe705f4beded9a2c685))

##### ただのDropBox APIの仕様によるものだが注意が必要

- ファイルの数が多いと`has_more`が`true`になり`entries`が省略されるので`files/list_folder/continue`で続きを読む必要がある

**Comment by kmyk** [comment]
@qryxip ありがとうございます。token がおかしいという情報を元に、Dropbox の app を作り直したら動くようになりました。
