### ISSUE TITLE
Codeforces login from terminal is broken and download samples requires login

### ISSUE THREAD

**Issue by Saurav-Paul** [online-judge-tools/api-client#73]
## Description
A few user from my project ai-virtual-assistant inform me they tried to login into codeforces that is not working. Then i looked it into this it seems like oj-api login for codeforces not working. i tried to login manually even tried to login using oj-tools still it is not working. I hope you will check it.

## Error log

```
INFO:root:online-judge-api-client 10.2.1
INFO:root:sleep 1.000000 sec
INFO:onlinejudge._implementation.logging:[-] unknown problem: https://codeforces.com/
INFO:onlinejudge._implementation.logging:[-] unknown contest: https://codeforces.com/
INFO:onlinejudge._implementation.logging:[x] service recognized: CodeforcesService.from_url('https://codeforces.com/'): https://codeforces.com/
INFO:onlinejudge._implementation.logging:[x] load cookie from: /home/saurav/.local/share/online-judge-tools/cookie.jar
INFO:onlinejudge._implementation.logging:[x] GET: https://codeforces.com/enter
INFO:onlinejudge._implementation.logging:[x] 200 OK
ERROR:root:
Traceback (most recent call last):
  File "/home/saurav/.local/lib/python3.8/site-packages/onlinejudge_api/main.py", line 279, in main
    result = login_service.main(service, username=parsed.username, password=parsed.password, check_only=parsed.check, session=session)
  File "/home/saurav/.local/lib/python3.8/site-packages/onlinejudge_api/login_service.py", line 40, in main
    service.login(get_credentials=get_credentials, session=session)
  File "/home/saurav/.local/lib/python3.8/site-packages/onlinejudge/service/codeforces.py", line 44, in login
    form = utils.FormSender(form, url=resp.url)
  File "/home/saurav/.local/lib/python3.8/site-packages/onlinejudge/_implementation/utils.py", line 61, in __init__
    assert isinstance(form, bs4.Tag)
AssertionError
```

**Comment by kmyk** [comment]
Thank you for reporting! It seems that there is an update of Codeforces and this breaks our code. I'll fix soon.

**Comment by kmyk** [comment]
Now the `/enter` redirects to `?f0a28=1` with JavaScript. why?

``` html
$ curl 'https://codeforces.com/enter'  
<html><body>Redirecting... Please, wait.<script type="text/javascript" src="/aes.min.js" ></script><script>function toNumbers(d){var e=[];d.replace(/(..)/g,function(d){e.push(parseInt(d,16))});return e}function toHex(){for(var d=[],d=1==arguments.length&&arguments[0].constructor==Array?arguments[0]:arguments,e="",f=0;f<d.length;f++)e+=(16>d[f]?"0":"")+d[f].toString(16);return e.toLowerCase()}var a=toNumbers("e9ee4b03c1d0822987185d27bca23378"),b=toNumbers("188fafdbe0f87ef0fc2810d5b3e34705"),c=toNumbers("ebe0e82fefc615e78c3acba688bf16b1");document.cookie="RCPC="+toHex(slowAES.decrypt(c,2,a,b))+"; expires=Thu, 31-Dec-37 23:55:55 GMT; path=/";document.location.href="https://codeforces.com/enter?f0a28=1";</script></body></html>
```

**Comment by kmyk** [comment]
I found blog posts about this
https://codeforces.com/blog/entry/80065
https://codeforces.com/blog/entry/80070

**Comment by kmyk** [comment]
related issue https://github.com/xalanq/cf-tool/issues/112

**Comment by Saurav-Paul** [comment]
Yeah it seems like recent change. That's why this problem suddenly start appearing.
Please let me know if you solve that issue.

**Comment by Saurav-Paul** [comment]
I checked the blogs. Lot's of people facing the bug

**Comment by kmyk** [comment]
This issue is difficult and I cannot fix immediately because this, the feature of RCPC tokens, is the feature to kill scraping scripts.
Of course the main target is scripts with terrible manners, but affects almost all tools including online-judge-tools, cf-tool, etc.

(BTW, the bug of RCPC tokens doesn't affects us.)

**Comment by Saurav-Paul** [comment]
If i could help you to solve this problem, it would awesome. But i don't have that great knowledge.
Yeah it's really very difficult.  I hope this problem will be solved.

RCPC token will not affect us that's awesome to hear.

**Comment by kmyk** [comment]
I found this problem also breaks the feature to download sample cases.

**Comment by Saurav-Paul** [comment]
Shit man, they makes it so complex... Now may be need to use oj login.... Today i will change my code and turn towards using webdriver.

**Comment by 9kin** [comment]
[I decided]( https://github.com/xalanq/cf-tool/issues/112#issuecomment-658026971)

**Comment by qryxip** [comment]
It seems that Codeforces reverted the change. (I found this while [trying to parse the `<script>` and compute RCPC value](https://gist.github.com/qryxip/ec0231554a58574ca99773cef97a1629))

![codeforces](https://user-images.githubusercontent.com/14125495/87583919-a551d400-c717-11ea-8dec-cebe7f46aee7.png)
